### ISSUE TITLE
IAP renewal checking

### ISSUE THREAD

**Issue by jb55** [damus-io/api#6]
To get around various testflight issues such as:

- https://github.com/damus-io/damus/issues/2149

We may need to write a script that periodically checks for new IAP transactions from apple after an account has expired on the server, so that the purple star can be automatically re-added even if the user has not opened the app

**Comment by jb55** [comment]
On Wed, May 15, 2024 at 11:55:23AM GMT, Daniel D’Aquino wrote:
>@alltheseas @jb55, I forgot to ask about this task on our last standup.
>Should we schedule it at some point? I want to make sure we are not
>forgetting it, especially now that many Purple users are probably on
>TestFlight

sure let's try to get this in the next sprint or one after

**Comment by alltheseas** [comment]
Added as placeholder for next sprint. Also created 1.9 API milestone (as we cannot group tickets from multiple projects in same milestone). I linked milestone repo with the Damus project.

In milestone view, under the Damus project, you can see API, alongside iOS, notedeck milestones. https://github.com/orgs/damus-io/projects/3/views/1

**Comment by danieldaquino** [comment]
While trying to help a customer with a similar problem, I had an idea for a solution to solve this. I decided to write a draft while the idea was still fresh in my mind.

https://github.com/danieldaquino/damus-api/commit/a07a9feaad93f799a95e2e00aecbd47f7eb85778

All automated tests are passing, but I haven't done functional testing to validate this actually addresses the problem.

**Comment by jb55** [comment]
On Wed, Jul 03, 2024 at 01:32:02PM GMT, Daniel D’Aquino wrote:
>While trying to help a customer with a similar problem, I had an idea for a solution to solve this. I decided to write a draft while the idea was still fresh in my mind.
>
>https://github.com/danieldaquino/damus-api/commit/a07a9feaad93f799a95e2e00aecbd47f7eb85778
>
>All automated tests are passing, but I haven't done functional testing to validate this actually addresses the problem.

yay! thank you.

**Comment by danieldaquino** [comment]
@jb55 finished refining and thoroughly testing this! Patches with all details were sent via email to patches@damus.io (https://groups.google.com/a/damus.io/g/patches/c/T-za_lk97Zs)

Please let me know if there are any concerns!
